//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Info
    {
        public Store_Info()
        {
            this.Store_Branches = new HashSet<Store_Branches>();
            this.Store_Sale = new HashSet<Store_Sale>();
        }
    
        public int Store_Info_ID { get; set; }
        public string Store_Name { get; set; }
        public Nullable<int> Utility_ID { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public string Updated_By { get; set; }
    
        public virtual ICollection<Store_Branches> Store_Branches { get; set; }
        public virtual Utility Utility { get; set; }
        public virtual ICollection<Store_Sale> Store_Sale { get; set; }
    }
}
