//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UtilitySaleDBContext : DbContext
    {
        public UtilitySaleDBContext()
            : base("name=UtilitySaleDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Users> Admin_Users { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Store_Branches> Store_Branches { get; set; }
        public virtual DbSet<Store_Info> Store_Info { get; set; }
        public virtual DbSet<Store_Sale> Store_Sale { get; set; }
        public virtual DbSet<Utility> Utilities { get; set; }
    }
}
